# Generated by Django 4.1.2 on 2024-06-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.IntegerField()),
                ('nombre_cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.categoria')),
            ],
        ),
    ]
